# Generated by Django 4.2 on 2025-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=6, verbose_name='Цена')),
                ('day', models.CharField(max_length=2, verbose_name='День мероприятия')),
                ('month', models.CharField(max_length=10, verbose_name='Месяц мероприятия')),
                ('start_date', models.CharField(help_text='25 мая, 2025', max_length=50, verbose_name='Дата начала')),
                ('time', models.CharField(help_text='12.30 - 02.30', max_length=50, verbose_name='Время проведения')),
                ('count_people', models.IntegerField(default=10, verbose_name='Количество участников')),
                ('location', models.CharField(max_length=100, verbose_name='Адрес')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('instructors', models.ManyToManyField(to='courses.instructors', verbose_name='Инструкторы')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
