# Generated by Django 5.2 on 2025-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_id_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='count_courses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество курсов с Ментором'),
        ),
    ]
