# Generated by Django 5.2 on 2025-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_instructors_count_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='count_students',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество выпускников Ментора'),
        ),
    ]
