# Generated by Django 5.2 on 2025-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_instructors_count_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='count_lessons',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Количество уроков'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='count_courses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Количество курсов с Ментором'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='count_students',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Количество выпускников Ментора'),
        ),
    ]
