# Generated by Django 5.2 on 2025-05-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_count_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructors',
            name='count_courses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество курсов с Ментором'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='count_students',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество выпускников Ментора'),
        ),
    ]
