# Generated by Django 5.2 on 2025-05-14 13:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_instructors_count_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, help_text='Например: 20 означает скидку 20%', null=True, verbose_name='Процентная скидка (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Например: -500 означает скидку  500 сомов', max_digits=12, null=True, verbose_name='Фиксированная скидка (в валюте)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='count_lessons',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество уроков'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
