# Generated by Django 5.2 on 2025-05-14 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='banner',
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, help_text='Например: 02:18:02', max_length=10, null=True, verbose_name='продолжительность видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='курс '),
        ),
    ]
