# Generated by Django 4.2 on 2025-05-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='media/', verbose_name='Баннер')),
                ('mini_banner', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Баннер поменьше')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count_comments', models.IntegerField(verbose_name='Кол-во комментраиев')),
                ('desc', models.TextField(verbose_name='Текст')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.instructors')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=155, verbose_name='email')),
                ('comment', models.TextField(verbose_name='Ваш комментрий')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
            options={
                'verbose_name': 'коммент',
                'verbose_name_plural': 'Комменты',
            },
        ),
    ]
