# Generated by Django 5.2 on 2025-05-14 13:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
