# Generated by Django 4.2 on 2025-05-07 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'вопрос/ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/', verbose_name='лого')),
                ('name', models.CharField(max_length=20, verbose_name='название сайта')),
                ('address', models.CharField(max_length=200, verbose_name='адресс')),
                ('phone', models.CharField(help_text='+996 554 97 70 13', max_length=17, verbose_name='номер')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='emaill')),
            ],
            options={
                'verbose_name': 'данные',
                'verbose_name_plural': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200, verbose_name='Главный заголовок')),
                ('on_title', models.CharField(max_length=100, verbose_name='Над заголовок')),
                ('under_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Под заголовок')),
                ('under_title_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Под заголовок 2')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_message', models.CharField(max_length=100, verbose_name='Главное сообщение')),
                ('desc', models.TextField(verbose_name='Подробнее')),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=5, verbose_name='Рейтинг')),
                ('name', models.CharField(max_length=200, verbose_name='Фио')),
                ('who_say', models.CharField(choices=[('Студент', 'Студент'), ('Ментор', 'Ментор')], default='Студент', max_length=10, verbose_name='Кто вы?')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='madia/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
