# Generated by Django 5.2 on 2025-05-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchased_at',
            new_name='created_at',
        ),
    ]
