# Generated by Django 5.2 on 2025-05-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_video_banner_video_duration_and_more'),
        ('settings', '0004_rename_purchased_at_purchase_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
