# Generated by Django 5.2 on 2025-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_video_banner_video_duration_and_more'),
        ('settings', '0005_reviews_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='course',
        ),
        migrations.AddField(
            model_name='reviews',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='courses.course'),
        ),
    ]
