# Generated by Django 5.2 on 2025-05-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_video_banner_video_duration_and_more'),
        ('settings', '0006_remove_reviews_course_reviews_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='course',
        ),
        migrations.AddField(
            model_name='purchase',
            name='course',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
