# Generated by Django 5.2 on 2025-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='лого для остальног сайта'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(upload_to='media/', verbose_name='лого только для index'),
        ),
    ]
