# Generated by Django 5.2 on 2025-05-30 13:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_settings_logo_2_alter_settings_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('under_title', models.CharField(max_length=30, verbose_name='Под заголовок')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('advantage_first', models.CharField(max_length=100, verbose_name='Наши приемущества/сильные стороны')),
                ('advantage_second', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наши приемущества/сильные стороны')),
                ('advantage_third', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наши приемущества/сильные стороны')),
                ('experience', models.IntegerField(default=5, verbose_name='Количество лет опыта')),
                ('banner_first', models.ImageField(upload_to='home', verbose_name='Первый баннер')),
                ('banner_second', models.ImageField(upload_to='home', verbose_name='Второй баннер')),
            ],
            options={
                'verbose_name': 'AboutUs_blog',
                'verbose_name_plural': 'AboutUs_blogs',
            },
        ),
    ]
