# Generated by Django 5.2 on 2025-05-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_aboutus_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus_blog',
            name='banner_second',
        ),
        migrations.AlterField(
            model_name='aboutus_blog',
            name='banner_first',
            field=models.ImageField(upload_to='home', verbose_name='Баннер'),
        ),
    ]
