# Generated by Django 5.2 on 2025-05-30 13:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_remove_aboutus_blog_banner_second_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='home', verbose_name='Иконка')),
                ('name', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'AboutUs_card',
                'verbose_name_plural': 'AboutUs_cards',
            },
        ),
    ]
