# Generated by Django 5.2 on 2025-05-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_aboutus_life'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='home', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
